# sysctl -w net.ipv6.conf.all.disable_ipv6=1
- name: Initialize the master
  shell: "kubeadm init  --pod-network-cidr=192.168.0.0/16 \
        --apiserver-advertise-address={{ kitchen | ternary( ansible_all_ipv4_addresses[1], ansible_default_ipv4.address) }} \
        {{ join_key | ternary( ' '.join(('--token', join_key)), '') }} \
        --token-ttl=48h0m0s"
  when: master_initialized.rc != 0

- name: deploying unzip
  package:
    name: "unzip"
# Deploying the ansible codebase if not yet, for completeness
- name: Fetching Ansible artifact from GH if Terraform didn't deploy it
  get_url:
    url: "https://github.com/samircury/kubernetes/archive/{{ ansible_branch }}.zip"
    dest: "/tmp/ansible.zip"
    mode: '0664'
  when: not ansible_codebase.stat.exists
- name: unpack-ansible
  unarchive:
    src: "/tmp/ansible.zip"
    dest: "/tmp/"
    remote_src: True
    creates: "/tmp/kubernetes-{{ansible_branch}}"
  when: not ansible_codebase.stat.exists
- name: Deploying ansible codebase
  copy:
    src: "/tmp/kubernetes-{{ansible_branch}}/ansible"
    remote_src: True
    dest: "/opt"
  when: not ansible_codebase.stat.exists

- name: Deploy Calico + Metrics Server
  shell: >
      kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f \
         /opt/ansible/roles/kubernetes/templates/calico.yml

      kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f \
        /opt/ansible/roles/kubernetes/templates/rbac-kdd.yml

      kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f \
        /opt/ansible/roles/kubernetes/templates/metrics-server/

- name: Keep kube running
  service:
    name: kubelet
    enabled: yes
    state: started