# sysctl -w net.ipv6.conf.all.disable_ipv6=1
## TODO: Implement passing a pre-generated join token via --token {{ join_key }}
- name: Initialize the master                                                  # {{ kitchen | ternary(  ansible_default_ipv4.address, ansible_all_ipv4_addresses[1]) }}
  shell: "kubeadm init  --pod-network-cidr=192.168.0.0/16 \
        --apiserver-advertise-address={{ kitchen |
          ternary( ansible_all_ipv4_addresses[1], ansible_default_ipv4.address) }} \
        --token-ttl=48h0m0s"
  # when: master_initialized.rc != 0
  # 	not_if "docker ps -a | grep kube-system"

## Download ansible in the master as an artifact. Or SCP the whole thing just in kitchen

# - name: Deploy Calico + Metrics Server
#   shell: >
#       kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /opt/ansible/ansible/roles/kubernetes/templates/calico.yml

#       kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /opt/ansible/ansible/roles/kubernetes/templates/rbac-kdd.yml

#       kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /opt/ansible/ansible/roles/kubernetes/templates/metrics-server/

# - name: Keep kube running
#   service:
#     name: kubelet
#     enabled: yes
#     state: started